version: "3.8"

services:
  app:
    image: tinycat-server
    build:
      context: .
    container_name: tinycat-api
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    env_file:
      - local.env

