version: "3.8"

services:
  app:
    image: tinycat-server
    build:
      context: .
    container_name: tinycat-api
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    env_file:
      - local.env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mylocalpassword
      - POSTGRES_DB=tinydb
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "0:5432"
    logging:
      # limit logs retained on host to 12.5MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "25"

volumes:
  postgres-data:
